environment: development
http:
  bind: 127.0.0.1:8000
  base_url: http://localhost:8000
database:
  connection_string: postgres://ohanaAdmin:ohanaMeansFamily@127.0.0.1:5432/ohana
redis:
  password: ohanaMeansFamily
  address: localhost:6379
  db: 0
authentication:
  config_url: http://localhost:8080
  client_id: ohana
  client_secret: family
  redirect_url: http://localhost:8000/auth/callback
  scopes: ['openid', 'profile', 'email', 'app.roles']
  roles_claim_name: roles
stitch:
  shards_location: shards/
node:
  server_name: alpaca # This is the name of the server in the cluster. Must be unique
  host_name: localhost
  bind_ip: 192.168.2.53
  port: 5555
  ca_cert: certificates/main_GLOBAL_CERTIFICATE.pem
  public_cert: certificates/output_cert.pem
  private_key: certificates/output_key.pem