environment: development
http:
  bind: 127.0.0.1:8000
  base_url: http://localhost:8000
database:
  connection_string: postgres://ohanaAdmin:ohanaMeansFamily@127.0.0.1:5432/ohana
redis:
  password: ohanaMeansFamily
  address: localhost:6379
  db: 0
authentication:
  config_url: http://localhost:8080
  client_id: ohana
  client_secret: family
  redirect_url: http://localhost:8000/auth/callback
stitch:
  shards_location: shards/
internode_communications:
  server_name: alpaca # This is the name of the server in the cluster. Must be unique
  host_name: localhost
  port: 5555
  ca_cert:
  public_cert:
  private_key: