version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14.2
    ports:
    - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ohanaAdmin
      POSTGRES_PASSWORD: ohanaMeansFamily
      POSTGRES_DB: ohana
    volumes:
    - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
    - "127.0.0.1:6379:6379"
    command: --requirepass ohanaMeansFamily

  oidc-server-mock:
    container_name: ohana-idp
    image: ghcr.io/soluto/oidc-server-mock:latest
    ports:
    - "127.0.0.1:8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      ACCOUNT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      USERS_CONFIGURATION_INLINE: |
        [
          {
            "SubjectId":"1",
            "Username":"admin",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "Ohana"
              },
              {
                "Type": "email",
                "Value": "admin@ohanais.live"
              },
              {
                "Type": "roles",
                "Value": "[\"admin\", \"some_role\"]",
                "ValueType": "json"
              }
            ]
          },
          {
            "SubjectId":"2",
            "Username":"user",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "John Doe"
              },
              {
                "Type": "email",
                "Value": "john@ohanais.live"
              },
              {
                "Type": "roles",
                "Value": "[\"test123\"]",
                "ValueType": "json"
              }
            ]
          },
          {
            "SubjectId":"3",
            "Username":"someone",
            "Password":"password",
            "Claims": [
              {
                "Type": "name",
                "Value": "Jane Doe"
              },
              {
                "Type": "email",
                "Value": "jane@ohanais.live"
              },
              {
                "Type": "roles",
                "Value": "[\"test123\"]",
                "ValueType": "json"
              }
            ]
          }
        ]
      IDENTITY_RESOURCES_INLINE: |
        [{
          "Name": "app.roles",
          "ClaimTypes": ["roles"]
        }]
      CLIENTS_CONFIGURATION_INLINE: |
        [{
            "ClientId": "ohana",
            "ClientSecrets": [
                "family"
            ],
            "Description": "Sample client",
            "AllowedGrantTypes": [
                "authorization_code"
            ],
            "RequirePkce": false,
            "AlwaysIncludeUserClaimsInIdToken": true,
            "RedirectUris": [
                "http://localhost:8000/auth/callback"
            ],
            "AllowedScopes": [
                "openid",
                "profile",
                "email",
                "app.roles"
            ],
            "ClientClaimsPrefix": "",
            "Claims": []

        }]
