environment: development
http:
  bind: 0.0.0.0:8001
  base_url: http://localhost:8001
database:
  connection_string: postgres://ohanaAdmin:ohanaMeansFamily@localhost:5432/ohana
redis:
  password: ohanaMeansFamily
  address: localhost:6379
  db: 0
authentication:
  config_url: http://localhost:8080
  client_id: ohana
  client_secret: family
  redirect_url: http://localhost:8000/auth/callback
  scopes: ['openid', 'profile', 'email', 'app.roles']
  roles_claim_name: roles
stitch:
  shards_location: shards/ohana1/
node:
  server_name: alpha
  host_name: localhost
  bind_ip: 192.168.2.53
  port: 5551
  ca_cert: certificates/main_GLOBAL_CERTIFICATE.pem
  public_cert: certificates/output_cert.pem
  private_key: certificates/output_key.pem
